import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { motion } from 'framer-motion';
import { FiZap } from 'react-icons/fi';
import toast from 'react-hot-toast';
import { createWorkerProfile, getMyWorkerProfile, updateWorkerProfile } from '../../services/workerService';
import { generateWorkerBio } from '../../services/aiService';
import { useAuth } from '../../context/AuthContext';
import Navbar from '../../components/common/Navbar';

const CATEGORIES = ['maid', 'cook', 'nurse', 'babysitter', 'caretaker', 'driver', 'gardener', 'housekeeper', 'elderly-care'];

const WorkerSetup = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const { register, handleSubmit, setValue, watch, formState: { errors, isSubmitting } } = useForm();

  const [existingProfile, setExistingProfile] = useState(null);
  const [generatingBio, setGeneratingBio] = useState(false);
  const [bioText, setBioText] = useState('');

  const watchedFields = watch(['name', 'category', 'experience', 'skills', 'languages']);

  useEffect(() => {
    getMyWorkerProfile()
      .then((res) => {
        const p = res.data.data;
        setExistingProfile(p);
        setValue('category', p.category);
        setValue('skills', p.skills?.join(', '));
        setValue('languages', p.languages?.join(', '));
        setValue('experience', p.experience);
        setValue('hourlyRate', p.hourlyRate);
        setValue('gender', p.gender);
        setValue('age', p.age);
        setValue('city', p.location?.city);
        setValue('state', p.location?.state);
        setValue('pincode', p.location?.pincode);
        setBioText(p.bio || '');
      })
      .catch(() => {});
  }, [setValue]);

  const handleGenerateBio = async () => {
    const [, category, experience, skills, languages] = watchedFields;
    if (!category) return toast.error('Select a category first');
    setGeneratingBio(true);
    try {
      const res = await generateWorkerBio({
        name: user?.name,
        category,
        experience: experience || 0,
        skills: skills || '',
        languages: languages || 'English',
      });
      setBioText(res.data.data.bio);
      toast.success('Bio generated by AI ✨');
    } catch {
      toast.error('AI generation failed');
    } finally {
      setGeneratingBio(false);
    }
  };

  const onSubmit = async (data) => {
    const formData = new FormData();
    formData.append('category', data.category);
    formData.append('skills', data.skills || '');
    formData.append('languages', data.languages || '');
    formData.append('experience', data.experience || 0);
    formData.append('hourlyRate', data.hourlyRate);
    if (data.gender) formData.append('gender', data.gender);
    if (data.age) formData.append('age', data.age);
    formData.append('bio', bioText);
    formData.append('location', JSON.stringify({ city: data.city, state: data.state, pincode: data.pincode }));
    if (data.photos?.[0]) {
      Array.from(data.photos).forEach((f) => formData.append('photos', f));
    }

    try {
      if (existingProfile) {
        await updateWorkerProfile(existingProfile._id, formData);
        toast.success('Profile updated!');
      } else {
        await createWorkerProfile(formData);
        toast.success('Profile created! Awaiting admin approval.');
      }
      navigate('/worker/dashboard');
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to save profile');
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />
      <div className="max-w-2xl mx-auto px-4 sm:px-6 py-10">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="text-2xl font-bold text-gray-900 mb-1">{existingProfile ? 'Edit Your Profile' : 'Setup Worker Profile'}</h1>
          <p className="text-gray-500 text-sm mb-8">Complete your profile to start receiving bookings.</p>

          <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
            <div className="card space-y-4">
              <h2 className="font-semibold text-gray-900">Basic Info</h2>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5">Category *</label>
                <select className="input bg-white" {...register('category', { required: 'Category required' })}>
                  <option value="">Select service category</option>
                  {CATEGORIES.map((c) => <option key={c} value={c}>{c.charAt(0).toUpperCase() + c.slice(1).replace('-', ' ')}</option>)}
                </select>
                {errors.category && <p className="text-red-500 text-xs mt-1">{errors.category.message}</p>}
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1.5">Experience (years)</label>
                  <input type="number" min="0" max="40" className="input" {...register('experience')} />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1.5">Hourly Rate (₹) *</label>
                  <input type="number" min="50" placeholder="e.g. 300" className="input"
                    {...register('hourlyRate', { required: 'Rate required', min: { value: 50, message: 'Min ₹50' } })} />
                  {errors.hourlyRate && <p className="text-red-500 text-xs mt-1">{errors.hourlyRate.message}</p>}
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1.5">Gender</label>
                  <select className="input bg-white" {...register('gender')}>
                    <option value="">Prefer not to say</option>
                    <option value="female">Female</option>
                    <option value="male">Male</option>
                    <option value="other">Other</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1.5">Age</label>
                  <input type="number" min="18" max="70" className="input" {...register('age')} />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5">Skills (comma separated)</label>
                <input placeholder="Cooking, Cleaning, Ironing" className="input" {...register('skills')} />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5">Languages (comma separated)</label>
                <input placeholder="Hindi, English, Bengali" className="input" {...register('languages')} />
              </div>
            </div>

            {/* AI Bio */}
            <div className="card space-y-3">
              <div className="flex items-center justify-between">
                <h2 className="font-semibold text-gray-900">Professional Bio</h2>
                <button type="button" onClick={handleGenerateBio} disabled={generatingBio}
                  className="flex items-center gap-1.5 text-sm text-primary-600 font-medium bg-primary-50 hover:bg-primary-100 px-3 py-1.5 rounded-lg transition-colors disabled:opacity-50">
                  <FiZap size={14} /> {generatingBio ? 'Generating...' : 'AI Generate ✨'}
                </button>
              </div>
              <textarea
                rows={4}
                value={bioText}
                onChange={(e) => setBioText(e.target.value)}
                placeholder="Write about your experience, skills, and work style..."
                className="input resize-none"
              />
              {bioText && <p className="text-xs text-gray-400">💡 AI-generated — feel free to edit</p>}
            </div>

            {/* Location */}
            <div className="card space-y-4">
              <h2 className="font-semibold text-gray-900">Location</h2>
              <div className="grid grid-cols-3 gap-3">
                <input placeholder="City" className="input col-span-1" {...register('city', { required: 'City required' })} />
                <input placeholder="State" className="input col-span-1" {...register('state')} />
                <input placeholder="Pincode" className="input col-span-1" {...register('pincode')} />
              </div>
              {errors.city && <p className="text-red-500 text-xs">{errors.city.message}</p>}
            </div>

            {/* Photos */}
            <div className="card">
              <h2 className="font-semibold text-gray-900 mb-3">Profile Photos</h2>
              <input type="file" accept="image/*" multiple className="text-sm text-gray-600 file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border-0 file:text-sm file:font-medium file:bg-primary-50 file:text-primary-700 hover:file:bg-primary-100"
                {...register('photos')} />
              <p className="text-xs text-gray-400 mt-2">Max 5 photos, JPG/PNG/WebP, up to 5MB each</p>
            </div>

            <button type="submit" disabled={isSubmitting} className="btn-primary w-full py-3">
              {isSubmitting ? 'Saving...' : existingProfile ? 'Update Profile' : 'Create Profile'}
            </button>
          </form>
        </motion.div>
      </div>
    </div>
  );
};

export default WorkerSetup;
